---
pool:
  vmImage: 'ubuntu-22.04'
trigger: 
  - main
stages:
  - stage: "Build"
    jobs:
      - job: "Build_JOB"
        steps:
          - task: "Npm@1"
            inputs:
              command: 'install'